spring:
  application:
    name: redis
#  세션 클러스터링 부분
#  session:
#    redis:
#      flush-mode: on_save
#      namespace: spring:session
  data:
    redis:
      port: 6379
      host: localhost

#      cache
#  cache:
#    type: redis

